### ISSUE TITLE
feat: update example creation instructions

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-examples/helia-examples#19]
I think instead of having users attempt to create an example repo under the ipfs-examples org, we should instead redirect them to the ipfs-examples/github-mgmt repo and have them create a PR for the new repository there, in addition to the PR to this repo for adding the example subfolder.

What do you think @achingbrain @galargh ?

**Comment by galargh** [comment]
Yes, you can totally create repos through github-mgmt. You can even automatically initialise them if you set [auto-init: true](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#auto_init).

**Comment by galargh** [comment]
I haven't tried that but it should also be possible to automatically initialise the repo using a specific template. See [template](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#template) param.
