### ISSUE TITLE
feat: Factor out common README.md sections into root

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-examples/helia-examples#20]
Came about during comments on https://github.com/ipfs-examples/helia-examples/pull/13. 

We should only have unique instructions in README.md and link to https://github.com/ipfs-examples/helia-examples/blob/main/README.md for anything that is repeated. 

### Highlighted quotes from the [comment thread](https://github.com/ipfs-examples/helia-examples/pull/13#discussion_r1139481846)

> There's a lot of boiler plate text that's shared between examples, I wish github markdown would allow import from other markdown files, it'd be much more manageable.

> I agree with the sentiment that it's too bad that Markdown can't import. Instead can we link to something like COMMON_README.md ? "Documentation", "Contributions", and "Want to hack on IPFS?" sections could all link to that so we have one place we update. (That can also be done as a followup PR that we apply to all the Helia examples.)

> I'm good to tackle after this PR. Can you create the issue for it to factor out these common parts? I think we can have better content for them, but want to give that feedback when it will be useful for all the examples, not just this one.

cc @whizzzkid @BigLep

**Comment by BigLep** [comment]
@SgtPooki : this seems like a nice/easy one to do for the examples to clean them up a bit.  do you think you could tackle before IPFS Thing?

**Comment by achingbrain** [comment]
The original intention of the structure of these examples was that the entry point is not this repo, but instead the individual example repos, for example https://github.com/ipfs-examples/helia-101

Each example was supposed to be self-contained, and it was accepted that there would be some level of duplication.

> so we have one place we update

The heavy lifting here is done by aegir's `check-project` command so it's close to zero effort to update them all in one go.

CI in this repo then takes care of pushing the changes out to each example repo.

If we want to add some specific config there for this repo - the documentation section for example, we could extend that command to read the common readme sections or whatever config from `.aegir.js` here.

**Comment by BigLep** [comment]
@achingbrain : understoo that each example should be self-contained.  There is a lot of boiler plate though in:
- About the project
- Generic getting started
- Documentation
- Contributing
- Want to hack on IPFS?

Some of those are things I think we should clean up, but right now it's multiple places.

My thinking is to add links from (for example) https://github.com/ipfs-examples/helia-examples/tree/main/examples/helia-101#contributing to something like https://github.com/ipfs-examples/helia-examples#contributing

If there's a template that aegir uses instead, I'm game to update that as well.

**Comment by SgtPooki** [comment]
Helia WG 2023-08-11

* Each example repo will mention the root examples repo and link to it
* Provide specific instructions for the example
* Link to root repo next steps doc (needs created)

We only maintain each examples instructions in each example (the different parts), we link to root repo for common links/knowledge (shared parts), and link to root repo next steps for that..
