### ISSUE TITLE
helia-nextjs example fails with error "missing required error components, refreshing..."

### ISSUE THREAD

**Issue by ianconsolata** [ipfs-examples/helia-examples#289]
When I run `npm i && npm run dev` in the `examples/helia-nextjs` folder, the app runs, but only displays a blank page with the error "missing required error components, refreshing...".

Refreshing does not seem to fix the issue.

**Comment by achingbrain** [comment]
I think you might be running into this error - https://github.com/vercel/next.js/issues/61105

**Comment by SgtPooki** [comment]
I can repro this error with the helia-nextjs example on main. This issue is resolved when downgrading to 14.0.4 as https://github.com/vercel/next.js/issues/61105#issuecomment-1926716066 states.

**Comment by ianconsolata** [comment]
Thanks for the speedy resolution!
