### ISSUE TITLE
feat: Example how to connect to an existing IPFS node the way it's possible with ipfs-http-client

### ISSUE THREAD

**Issue by dievardump** [ipfs-examples/helia-examples#68]
I am using third-party service to run my IPFS nodes.

Until now, I was using [ipfs-http-client](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client/) to auth and connect to those nodes and be able to add my content to it.

`ipfs-http-client` now shows a big deprecated sign so I would like to migrate to Helia.

Problem is I do not find any indication how to do that. Helia seems to be centered around "running your own node", which is something that is of no interest to me right now. 

I want to be able to connect to an existing IPFS node (with my credentials too!) and be able to do my IPFS tasks (pin, unpin, ...) against it.

How can we achieve that with the current library?!

**Comment by SgtPooki** [comment]
@dievardump Thanks for the clear explanation of the problem you're running into.

You should look into using [kubo-rpc-client](https://github.com/ipfs/js-kubo-rpc-client) for accessing a node via the Kubo RPC API. kubo-rpc-client is the replacement for ipfs-http-client.

I'm closing this issue but please feel free to re-open if you have questions/concerns!
